services:
  minimal-api-project-sample:
    image: minimal-api-project-sample
    container_name: minimal-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5145:5145"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=5145
      - ASPNETCORE_URLS=http://+:5145
    networks:
      - minimal-api-network

networks:
  minimal-api-network:
    driver: bridge
